[package]
name = "clara"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.42", features = ["derive"] }
directories = "6.0.0"
rusqlite = "0.37.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.4"
